# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20161004_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(default='images/te1.jpg', max_length=200, null=True)),
                ('reg_num', models.CharField(max_length=20)),
            ],
        ),
    ]
