# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_member_student_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='student_num',
            field=models.IntegerField(null=True),
        ),
    ]
