# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20161006_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.CharField(default='images/dsa1.png', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='image',
            field=models.CharField(default='images/dsa1.png', max_length=200, null=True),
        ),
    ]
