# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20170112_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
